
trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'  
      goals: 'package'


  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/target'
      artifactName: 'drop'
      publishLocation: 'Pipeline'

 
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'c65909bf-6186-4598-a89e-54db01bd8434'
      appType: 'webApp'
      WebAppName: 'AImpress'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.jar'
